apiVersion: v1
kind: Secret
metadata:
  name: dockerio
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJpbnRlcmVzdGluZ3N0b3JhZ2UiLCJwYXNzd29yZCI6IjMwZTRjYThmLWEwMzUtNDRkNS1hZDQyLWY5NDg3YjcwMjFiNSIsImF1dGgiOiJhVzUwWlhKbGMzUnBibWR6ZEc5eVlXZGxPak13WlRSallUaG1MV0V3TXpVdE5EUmtOUzFoWkRReUxXWTVORGczWWpjd01qRmlOUT09In19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: find-a-store-service
spec:
  selector:
    matchLabels:
      app: find-a-store-service
  template:
    metadata:
      labels:
        app: find-a-store-service
    spec:
      containers:
        - name: server
          image: docker.io/interestingstorage/buytime-find-a-store-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9339
          env:
            - name: MYSQL_HOST
              value: "buytime-database.internal"
            - name: MYSQL_DB
              value: "store_location"
      imagePullSecrets:
        - name: dockerio
---
apiVersion: v1
kind: Service
metadata:
  name: find-a-store-service
spec:
  type: ClusterIP
  selector:
    app: find-a-store-service
  ports:
    - name: http
      port: 80
      targetPort: 9339
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: docker.io/interestingstorage/buytime-frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerio            
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
